/*
 * Copyright (C) 2026 Ctrip.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ctrip.sqllin.dsl.sql

import com.ctrip.sqllin.dsl.annotation.ExperimentalDSLDatabaseAPI

/**
 * An FTS3 or FTS4 full-text search table, which [Table]'s operations write to and read like any table, and which
 * `MATCH` searches.
 *
 * FTS table objects are generated by sqllin-processor for `@DBRow` classes annotated with
 * [@Fts4][com.ctrip.sqllin.dsl.annotation.Fts4] or [@Fts3][com.ctrip.sqllin.dsl.annotation.Fts3].
 *
 * @param T The type of the table's rows
 *
 * @author Yuang Qiao
 */
@ExperimentalDSLDatabaseAPI
public abstract class FtsTable<T>(tableName: String) : Table<T>(tableName)
