/*
 * Copyright (C) 2022 Ctrip.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ctrip.sqllin.dsl.sql

import com.ctrip.sqllin.dsl.annotation.ExperimentalDSLDatabaseAPI
import kotlinx.serialization.KSerializer

/**
 * What a SELECT reads: a [Table], or a [View].
 *
 * A relation names the table or view and gives the serializer of its rows, which is all a query needs, as a property
 * is read from the column of the same name. Only a [Table] can be written to, created with `CREATE` and altered.
 *
 * @param T The type of the rows
 * @property tableName The name of the table or view in SQLite
 *
 * @author Yuang Qiao
 */
public abstract class Relation<T> internal constructor(
    internal val tableName: String,
) {
    /**
     * Returns the kotlinx.serialization serializer for the entity type.
     *
     * Used internally for serializing entities to SQL INSERT/UPDATE statements
     * and deserializing query results to entity objects.
     */
    public abstract fun kSerializer(): KSerializer<T>

    /**
     * The relation as written after FROM or JOIN: its name, or the subquery of a derived table with its alias.
     */
    internal open val fromSQL: String
        get() = tableName

    /**
     * The parameters of [fromSQL], which a statement binds before those of its other clauses.
     */
    internal open val fromParameters: List<Any?>
        get() = emptyList()

    /**
     * The tables and views a query of this relation reads, which an observed query watches.
     */
    internal open val readTables: Set<String>
        get() = setOf(tableName)
}

/**
 * Abstract base class representing a SQLite table with type-safe DSL operations.
 *
 * Table objects are typically generated by the sqllin-processor KSP plugin for data classes
 * annotated with [@DBRow][com.ctrip.sqllin.dsl.annotation.DBRow]. Each generated table object
 * (named `{ClassName}Table`) extends this class and provides:
 *
 * - Type-safe column property accessors for building SQL clauses
 * - Serialization support via kotlinx.serialization
 * - Primary key metadata for INSERT/UPDATE operations
 *
 * Table objects are used as receivers for DSL operations within [com.ctrip.sqllin.dsl.DatabaseScope]:
 *
 * Example:
 * ```kotlin
 * @Serializable
 * @DBRow
 * data class Person(val id: Long?, val name: String, val age: Int)
 *
 * // Generated by processor: object PersonTable : Table<Person>("Person") { ... }
 *
 * database {
 *     PersonTable INSERT person
 *     PersonTable SELECT WHERE(PersonTable.age GTE 18)
 * }
 * ```
 *
 * @param T The entity type this table represents
 * @property tableName The name of the SQLite table
 *
 * @author Yuang Qiao
 */
public abstract class Table<T>(tableName: String) : Relation<T>(tableName) {

    /**
     * Metadata about the table's primary key configuration.
     *
     * - `null` if the table has no primary key
     * - Contains information about single or composite primary keys, including
     *   whether the key is auto-incrementing or backed by SQLite's rowid
     *
     * This information is extracted from [@PrimaryKey][com.ctrip.sqllin.dsl.annotation.PrimaryKey]
     * and [@CompositePrimaryKey][com.ctrip.sqllin.dsl.annotation.CompositePrimaryKey] annotations
     * during code generation.
     */
    public abstract val primaryKeyInfo: PrimaryKeyInfo?

    /**
     * The complete CREATE TABLE SQL statement for this table.
     *
     * This property contains a fully-formed CREATE TABLE statement generated at compile-time
     * by the sqllin-processor KSP plugin. The statement includes:
     * - Table name
     * - All non-transient columns with appropriate SQLite types
     * - Column constraints (PRIMARY KEY, NOT NULL, UNIQUE, COLLATE NOCASE)
     * - Table-level constraints (composite primary keys, composite unique constraints)
     *
     * ### Generation Details
     * - Generated during annotation processing from [@DBRow][com.ctrip.sqllin.dsl.annotation.DBRow] classes
     * - Kotlin types are mapped to SQLite types (Int→INT, String→TEXT, etc.)
     * - Annotations like [@PrimaryKey], [@Unique], [@CollateNoCase], etc. add corresponding SQL clauses
     * - Enum properties are stored as INTEGER (ordinal values)
     *
     * ### Example
     * For a data class:
     * ```kotlin
     * @Serializable
     * @DBRow
     * data class User(
     *     @PrimaryKey(autoIncrement = true) val id: Long?,
     *     @Unique @CollateNoCase val email: String,
     *     val name: String,
     *     val age: Int
     * )
     * ```
     *
     * The generated `createSQL` would be:
     * ```sql
     * CREATE TABLE User(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT COLLATE NOCASE UNIQUE,name TEXT,age INT)
     * ```
     *
     * ### Performance Note
     * Since this is generated at compile-time, there is no runtime overhead for constructing
     * the CREATE TABLE statement, unlike previous versions that built it at runtime.
     *
     * @see com.ctrip.sqllin.dsl.annotation.DBRow
     * @see com.ctrip.sqllin.dsl.annotation.PrimaryKey
     * @see com.ctrip.sqllin.dsl.annotation.Unique
     * @see com.ctrip.sqllin.dsl.annotation.CompositeUnique
     * @see com.ctrip.sqllin.dsl.annotation.CollateNoCase
     */
    public abstract val createSQL: String
}

/**
 * Returns a table with the structure of this one under another [name], as needed to rebuild a table.
 *
 * SQLite's `ALTER TABLE` can only rename a table, and add, rename or drop a column; dropping one needs SQLite 3.35,
 * which Android only has from API 34 on. Any other change, such as adding a constraint or changing the primary key,
 * rebuilds the table: create the new structure under a temporary name, copy the rows with `INSERT INTO ... SELECT`,
 * drop the old table, and rename the new one:
 * ```kotlin
 * val newPerson = PersonTable.withName("person_new")
 * CREATE(newPerson)
 * newPerson INSERT (PersonV1Table SELECT listOf(PersonV1Table.name AS Person::fullName))
 * DROP(PersonV1Table)
 * "person_new" ALTER_RENAME_TABLE_TO PersonTable
 * ```
 * Here `PersonV1` is a `@DBRow` class that keeps the old structure, under the same table name as `Person`.
 *
 * Rename the new table, not the old one: renaming a table also renames the references to it in other tables'
 * foreign keys, with SQLite's default settings, so the references would follow the old table and be left pointing
 * at a table that no longer exists once it's dropped.
 *
 * The returned table has no column properties, as those of this table name this table. It is meant for statements
 * on the table as a whole: `CREATE`, `INSERT`, `DROP` and `ALTER_RENAME_TABLE_TO`. The table of an [FtsTable] is an
 * [FtsTable] too, with the same options, which is how an FTS table is rebuilt with other ones.
 *
 * @param name The name of the returned table
 * @return A table with this table's columns, constraints and row type, named [name]
 */
@OptIn(ExperimentalDSLDatabaseAPI::class)
public fun <T> Table<T>.withName(name: String): Table<T> {
    require(name.isNotBlank()) { "The name of a table can't be blank." }
    return if (this is FtsTable<T>) NamedFtsTable(this, name) else NamedTable(this, name)
}

/**
 * A table with the structure of [table] under another name.
 */
private class NamedTable<T>(private val table: Table<T>, name: String) : Table<T>(name) {

    override fun kSerializer(): KSerializer<T> = table.kSerializer()

    override val primaryKeyInfo: PrimaryKeyInfo?
        get() = table.primaryKeyInfo

    override val createSQL: String = table.createSQLNamed(name)
}

/**
 * An FTS table with the structure of [table] under another name.
 */
@OptIn(ExperimentalDSLDatabaseAPI::class)
private class NamedFtsTable<T>(private val table: FtsTable<T>, name: String) : FtsTable<T>(name) {

    override fun kSerializer(): KSerializer<T> = table.kSerializer()

    override val primaryKeyInfo: PrimaryKeyInfo?
        get() = table.primaryKeyInfo

    override val createSQL: String = table.createSQLNamed(name)
}

/**
 * Returns the CREATE statement of this table with `IF NOT EXISTS`, which does nothing if a table of its name exists:
 * `CREATE TABLE IF NOT EXISTS name(...)`, or `CREATE VIRTUAL TABLE IF NOT EXISTS name USING ...`.
 */
internal fun Table<*>.createSQLIfNotExists(): String {
    for (start in listOf("CREATE TABLE ", "CREATE VIRTUAL TABLE ")) {
        if (createSQL.startsWith(start))
            return "${start}IF NOT EXISTS ${createSQL.substring(start.length)}"
    }
    error("The CREATE statement of table '$tableName' doesn't start with 'CREATE TABLE ' or 'CREATE VIRTUAL TABLE '.")
}

/**
 * Returns the CREATE statement of this table with [name] in place of its own: `CREATE TABLE name(...)`, or
 * `CREATE VIRTUAL TABLE name USING ...` for a virtual table.
 */
private fun Table<*>.createSQLNamed(name: String): String {
    for ((start, end) in listOf("CREATE TABLE " to "(", "CREATE VIRTUAL TABLE " to " USING ")) {
        val prefix = "$start$tableName$end"
        if (createSQL.startsWith(prefix))
            return "$start$name$end${createSQL.substring(prefix.length)}"
    }
    error("The CREATE statement of table '$tableName' doesn't start with 'CREATE TABLE $tableName(' or 'CREATE VIRTUAL TABLE $tableName USING '.")
}