/*
 * Copyright (C) 2026 Ctrip.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ctrip.sqllin.dsl.sql

import com.ctrip.sqllin.dsl.annotation.ExperimentalDSLDatabaseAPI

/**
 * A SQLite view, which a SELECT reads like a table.
 *
 * View objects are generated by sqllin-processor for classes annotated with
 * [@DBView][com.ctrip.sqllin.dsl.annotation.DBView]: the view of a class `Adult` is the object `AdultView`, with a
 * property for each column. A view is created with `CREATE_VIEW(AdultView) AS (select)` and dropped with
 * `DROP(AdultView)`. As it isn't a [Table], it can't be written to, created with `CREATE`, or altered.
 *
 * @param T The type of the view's rows
 *
 * @author Yuang Qiao
 */
@ExperimentalDSLDatabaseAPI
public abstract class View<T>(viewName: String) : Relation<T>(viewName)

/**
 * The view to create, as `CREATE_VIEW(view)` starts. It becomes a statement once `AS` gives it its SELECT.
 *
 * @param T The type of the view's rows
 *
 * @author Yuang Qiao
 */
@ExperimentalDSLDatabaseAPI
public class ViewDefinition<T> internal constructor(internal val view: View<T>, internal val isIfNotExists: Boolean = false)
