# Publish artifacts on Linux env
./gradlew :sqllin-driver:publishLinuxX64PublicationToMavenCentralRepository
./gradlew :sqllin-driver:publishLinuxArm64PublicationToMavenCentralRepository
./gradlew :sqllin-processor:publishMavenPublicationToMavenCentralRepository
./gradlew :sqllin-dsl:publishLinuxX64PublicationToMavenCentralRepository
./gradlew :sqllin-dsl:publishLinuxArm64PublicationToMavenCentralRepository